image:
  file: .cde.Dockerfile

tasks:
  - name: Build & Run Container
    init: sh ./cde/docker_build.sh
    command: |
      sh ./cde/docker_run.sh
      gp sync-done dockerrun
  - name: Open Swagger
    command: |
      gp sync-await dockerrun
      gp preview $(gp url 8000)/swagger/index.html

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.csharp
    - ms-azuretools.vscode-docker